name: Test and Deploy Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y libcap-dev build-essential

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover -s tests

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Debug Environment
      run: |
        echo "Current HOME: $HOME"
        ls -ld /home/runner
        ls -ld /home/runner/.ssh || echo "No .ssh directory exists"

    - name: Add SSH key
      run: |
        mkdir -p /tmp/ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > /tmp/ssh/id_rsa
        chmod 600 /tmp/ssh/id_rsa
        ssh-keyscan -H ${{ secrets.PI_IP }} >> /tmp/ssh/known_hosts
      shell: bash

    - name: Deploy to Raspberry Pi
      run: |
        ssh -i /tmp/ssh/id_rsa -o StrictHostKeyChecking=no pi@${{ secrets.PI_IP }} "
          cd ~/Zakibot &&
          git pull origin main &&
          sudo cp ~/Zakibot/zakibot.service /etc/systemd/system/ &&
          sudo systemctl daemon-reload &&
          sudo systemctl enable zakibot.service &&
          sudo systemctl restart zakibot.service
        "
      env:
        PI_IP: ${{ secrets.PI_IP }}
