name: Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y libcap-dev build-essential

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover -s tests

  deploy:
      needs: test
      runs-on: ubuntu-latest
      if: github.ref == 'refs/heads/main'

      steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug SSH Key Setup
        run: |
          echo "Current HOME: $HOME"
          ls -ld ~/.ssh || echo "No .ssh directory exists"

      - name: Debug SSH Key Setup
        run: |
          echo "Current HOME: $HOME"
          ls -la ~/.ssh || echo "No .ssh directory exists yet."
          ls -ld $HOME || echo "Home directory not accessible."

      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.PI_IP }} >> ~/.ssh/known_hosts
        shell: bash

      - name: Deploy to Raspberry Pi
        run: |
          ssh pi@${{ secrets.PI_IP }} "
            cd ~/Zakibot &&
            git pull origin main &&
            sudo cp ~/Zakibot/zakibot.service /etc/systemd/system/ &&
            sudo systemctl daemon-reload &&
            sudo systemctl enable zakibot.service &&
            sudo systemctl restart zakibot.service
          "
        env:
          PI_IP: ${{ secrets.PI_IP }}